[tool.poetry]
name = "fast-api"
version = "0.1.0"
description = ""
authors = ["Giorbis"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.6"
uvicorn = "^0.24.0.post1"
fastapi = "^0.104.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
